name: Default Plan Unit Tests
on:
  push:
    branches: ['**'] # '*' will cause the workflow to run on all commits to all branches.

jobs:
  go-tests:
    name: Default Plan Unit Tests
    runs-on: ubuntu-latest
    environment: terraformSecrets
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t viya4-iac-azure:terratest -f Dockerfile.terratest .
      - name: Run Tests
        working-directory: test
        run: |
          mkdir -p $(pwd)/results
          docker run \
            -e TF_VAR_subscription_id=$TF_VAR_subscription_id \
            -e TF_VAR_tenant_id=$TF_VAR_tenant_id \
            -e TF_VAR_client_id=$TF_VAR_client_id \
            -e TF_VAR_client_secret=$TF_VAR_client_secret \
            -v $(pwd)/results:/results \
            viya4-iac-azure:terratest
        env:
          # TF ENVIRONMENT
          TF_VAR_subscription_id: "${{ secrets.TF_VAR_SUBSCRIPTION_ID }}"
          TF_VAR_tenant_id: "${{ secrets.TF_VAR_TENANT_ID }}"
          TF_VAR_client_id: "${{ secrets.TF_VAR_CLIENT_ID }}"
          TF_VAR_client_secret: "${{ secrets.TF_VAR_CLIENT_SECRET }}"
      - name: Convert to JUnit XML
        uses: jstemmer/go-junit-report@v0.9.1
        with:
          input: test/results/report.xml
          output: test/junit/junit-report.xml
      - name: Report JUnit Results
        uses: mikepenz/action-junit-report@v2
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: test/junit/junit-report.xml
