name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
jobs:
  update-semver:
    # Update the tags based on semantic versioning.
    # Also update the latest tag.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
      - name: Create latest git tag
        run: |
          git tag latest
      - name: Push latest git tag
        run: git push -f origin latest