name: 'Mark stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity.'
          days-before-stale: 30
          days-before-close: -1